// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdwavdiuvdvovoypxrny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkd2F2ZGl1dmR2b3ZveXB4cm55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMDI2MDUsImV4cCI6MjA2Njc3ODYwNX0.zbWpi2oMmPZNbd1FeBBln7YYrU_Q9X7T4UjOF5Z8Q5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});